image: golang:1.10

variables:
  GOPACKAGE: go.htdvisser.nl/eui

cache:
  paths:
  - .go/src/github.com/golang
  - .go/pkg/dep
  - .go/tmp

before_script:
- export GOPATH=$(realpath .)/.go
- if [[ ! -d $GOPATH ]]; then mkdir -p $GOPATH; fi
- export PATH="$PATH:$GOPATH/bin"
- export GOTMPDIR=$GOPATH/tmp
- if [[ ! -d $GOTMPDIR ]]; then mkdir -p $GOTMPDIR; fi
- go get -u github.com/golang/dep/cmd/dep
- mkdir -p $GOPATH/src/$(dirname $GOPACKAGE)
- ln -svf $CI_PROJECT_DIR $GOPATH/src/$GOPACKAGE
- cd $GOPATH/src/$GOPACKAGE
- dep ensure -v -vendor-only

stages:
- test

test:
  stage: test
  script:
  - go fmt ./...
  - go vet ./...
  - go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
  - bash <(curl -s https://codecov.io/bash)
