image: golang:1.10

cache:
  paths:
  - .go/src/v
  - .go/tmp

before_script:
- export GOPATH=$(realpath .)/.go
- if [[ ! -d $GOPATH ]]; then mkdir -p $GOPATH; fi
- export PATH="$PATH:$GOPATH/bin"
- export GOTMPDIR=$GOPATH/tmp
- if [[ ! -d $GOTMPDIR ]]; then mkdir -p $GOTMPDIR; fi
- make dev-deps

stages:
- test
- build

test:
  stage: test
  script:
  - vgo test -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
  - vgo fmt ./...
  - vgo vet ./...

build:
  stage: build
  artifacts:
    paths:
    - dist
  script:
  - if [[ ! -d dist ]]; then mkdir dist; fi
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 make build
