image: golang:1.11rc2

cache:
  paths:
  - .go/pkg/mod

before_script:
- export GOPATH=$(realpath .)/.go
- if [[ ! -d $GOPATH ]]; then mkdir -p $GOPATH; fi
- export PATH="$PATH:$GOPATH/bin"
- export GOTMPDIR=$GOPATH/tmp
- if [[ ! -d $GOTMPDIR ]]; then mkdir -p $GOTMPDIR; fi

stages:
- test
- build

test:
  stage: test
  script:
  - go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go fmt ./...

build:
  stage: build
  artifacts:
    paths:
    - dist
  script:
  - if [[ ! -d dist ]]; then mkdir dist; fi
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 make build
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 make build
